apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: f3g1vgciz-java-quarkus
  janus-idp.io/tekton: f3g1vgciz-java-quarkus
  backstage.io/kubernetes-id: f3g1vgciz-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f3g1vgciz-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
